In [1]:
import torch


In [6]:
inputs = torch.tensor([[[[1., 2.],
                         [3., 4.]]]])

inputs.shape

torch.Size([1, 1, 2, 2])

In [14]:
fc = torch.nn.Linear(4, 2)

weights = torch.tensor([[1.1, 1.2, 1.3, 1.4],
                        [1.5, 1.6, 1.7, 1.8]])
bias = torch.tensor([1.9, 2.0])
fc.weight.data = weights
fc.bias.data = bias

torch.relu(fc(inputs.view(-1, 4)))

tensor([[14.9000, 19.0000]], grad_fn=<ReluBackward0>)

In [16]:

conv = torch.nn.Conv2d(in_channels=1,
                       out_channels=2,
                       kernel_size=inputs.squeeze(dim=(0)).squeeze(dim=(0)).size())
print(conv.weight.size())
print(conv.bias.size())
conv.weight.data = weights.view(2, 1, 2, 2)
conv.bias.data = bias

torch.relu(conv(inputs))

torch.Size([2, 1, 2, 2])
torch.Size([2])


tensor([[[[14.9000]],

         [[19.0000]]]], grad_fn=<ReluBackward0>)

In [17]:

conv = torch.nn.Conv2d(in_channels=4,
                       out_channels=2,
                       kernel_size=(1, 1))

conv.weight.data = weights.view(2, 4, 1, 1)
conv.bias.data = bias
torch.relu(conv(inputs.view(1, 4, 1, 1)))

tensor([[[[14.9000]],

         [[19.0000]]]], grad_fn=<ReluBackward0>)